let weatherConditions = {
    'scattered clouds': 'Party Cloudy',
    'overcast clouds': 'Mostly Cloudy',
    'clear sky': 'Clear Skies',
    'few clouds': 'Mostly Clear',
    'thunderstorm': 'Thunderstorm',
    'thunderstorm with light rain': 'Thunderstorm with Light Rain',
    'thunderstorm with rain': 'Thunderstorm',
    'thunderstorm with heavy rain': 'Thunderstorm with Heavy Rain',
    'light thunderstorm': 'Light Thunderstorm',
    'thunderstorm': 'Thunderstorm',
    'heavy thunderstorm': 'Heavy Thunderstorm',
    'ragged thunderstorm': 'Isolated Thunderstorm',
    'thunderstorm with light drizzle': 'Thunderstorm with Light Drizzle',
    'thunderstorm with drizzle': 'Thunderstorm with Drizzle',
    'thunderstorm with heavy drizzle': 'Thunderstorm with Rain',
    'light intensity drizzle': 'Light Drizzle',
    'drizzle': 'Drizzle',
    'heavy intensity drizzle': 'Heavy Drizzle',
    'light intensity drizzle rain': 'Light Rain',
    'drizzle rain': 'Light Rain',
    'heavy intensity drizzle rain': 'Heavy Rain',
    'shower rain and drizzle': 'Rain Shower',
    'heavy shower rain and drizzle': 'Heavy Rain Shower',
    'shower drizzle': 'Shower Drizzle',
    'light rain': 'Light Rain Showers',
    'moderate rain': 'Moderate Rain',
    'heavy intensity rain': 'Heavy Intensity Rain',
    'freezing rain': 'Hail',
    'light intensity shower rain': 'Light Rain Shower',
    'shower rain': 'Rain Shower',
    'heavy intensity shower rain': 'Heavy Rain Shower',
    'ragged shower rain': 'Isolated Rain Shower',
    'light snow': 'Light Snow',
    'Snow': 'Snow',
    'Heavy snow': 'Heavy snow',
    'Sleet': 'Sleet',
    'Light shower sleet': 'Light Sleet Shower',
    'Shower sleet': 'Sleet Shower',
    'Light rain and snow': ' Light Snow and Rain',
    'Rain and snow': 'Snow and Rain',
    'Light shower snow': 'Light Snow Shower',
    'Heavy shower snow': 'Heavy Snow Shower',
    'Shower snow': 'Snow Shower',
    'Heavy shower snow': 'Heavy Snow Shower',
    'mist': 'Misty',
    'rain': 'Rain',
    'Smoke': 'Smokey',
    'Haze': 'Hazy',
    'fog': 'Foggy',
    'sand': 'Sand storm',
    'dust': 'Dusty',
    'volcanic ash': 'Volcanic Ash',
    'Squalls': 'Very Windy',
    'tornado': 'Tornado',
    'clear sky': 'Clear Sky',
    'sand/ dust whirls': 'Sand / Dust Tornados'
}

export default weatherConditions;